"""Send the weekly job digest via Gmail SMTP."""
import logging
import os
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from html import escape
from typing import List, Dict

logger = logging.getLogger(__name__)


def _score_color(score: int) -> str:
    if score >= 85:
        return "#1a7f37"  # green
    if score >= 75:
        return "#9a6700"  # amber
    return "#656d76"      # grey


def _build_job_card(job: Dict) -> str:
    score = job.get("score", 0)
    color = _score_color(score)
    title = escape(job.get("title", "Untitled"))
    company = escape(job.get("company", "Unknown"))
    location = escape(job.get("location", ""))
    source = escape(job.get("source", ""))
    url = escape(job.get("url", "#"))
    reason = escape(job.get("reason", ""))
    red_flags = escape(job.get("red_flags", "") or "")
    is_remote = "Remote" if job.get("is_remote") else "On-site / Hybrid"
    
    red_flag_block = (
        f'<div style="margin-top:8px;color:#cf222e;font-size:13px;"><strong>Watch out:</strong> {red_flags}</div>'
        if red_flags and red_flags.lower() not in ("", "none", "n/a", "parse_error")
        else ""
    )
    
    return f"""
    <div style="border:1px solid #d0d7de;border-radius:8px;padding:16px;margin-bottom:14px;background:#fff;">
      <div style="display:flex;justify-content:space-between;align-items:flex-start;gap:12px;">
        <div style="flex:1;">
          <div style="font-size:17px;font-weight:600;color:#0969da;">
            <a href="{url}" style="color:#0969da;text-decoration:none;">{title}</a>
          </div>
          <div style="font-size:14px;color:#1f2328;margin-top:4px;">
            <strong>{company}</strong> &middot; {location} &middot; {is_remote}
          </div>
        </div>
        <div style="background:{color};color:#fff;padding:6px 12px;border-radius:20px;font-weight:600;font-size:14px;white-space:nowrap;">
          {score}/100
        </div>
      </div>
      <div style="margin-top:10px;color:#1f2328;font-size:14px;line-height:1.5;">
        {reason}
      </div>
      {red_flag_block}
      <div style="margin-top:10px;font-size:12px;color:#656d76;">
        Source: {source}
      </div>
    </div>
    """


def _build_email_html(jobs: List[Dict]) -> str:
    today = datetime.utcnow().strftime("%B %d, %Y")
    if not jobs:
        body = """
        <div style="padding:24px;background:#fff8c5;border-radius:8px;color:#1f2328;">
          <strong>Quiet week.</strong> No roles cleared the score threshold this run.
          Could be a low-volume week, or some sources may have been rate-limited.
          Check the GitHub Actions log if this repeats.
        </div>
        """
    else:
        cards = "".join(_build_job_card(j) for j in jobs)
        body = f"""
        <div style="margin-bottom:16px;color:#1f2328;font-size:15px;">
          {len(jobs)} curated role{'s' if len(jobs) != 1 else ''} for you this week, sorted by fit.
        </div>
        {cards}
        """
    
    return f"""
    <html>
      <body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#f6f8fa;padding:24px;margin:0;">
        <div style="max-width:680px;margin:0 auto;">
          <div style="margin-bottom:20px;">
            <div style="font-size:22px;font-weight:700;color:#1f2328;">Weekly PM Digest</div>
            <div style="font-size:13px;color:#656d76;margin-top:2px;">{today}</div>
          </div>
          {body}
          <div style="margin-top:24px;padding-top:16px;border-top:1px solid #d0d7de;font-size:12px;color:#656d76;">
            Verify Glassdoor / AmbitionBox ratings manually before applying.
            Generated by your job agent.
          </div>
        </div>
      </body>
    </html>
    """


def send_digest(jobs: List[Dict]) -> None:
    """Send the email. Reads creds from env vars."""
    sender = os.environ.get("GMAIL_SENDER")
    app_password = os.environ.get("GMAIL_APP_PASSWORD")
    recipient = os.environ.get("EMAIL_RECIPIENT", sender)
    
    if not sender or not app_password:
        raise RuntimeError("GMAIL_SENDER or GMAIL_APP_PASSWORD not set")
    
    today = datetime.utcnow().strftime("%b %d")
    subject = f"PM Job Digest - {today} - {len(jobs)} roles"
    
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = recipient
    msg.attach(MIMEText(_build_email_html(jobs), "html"))
    
    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, timeout=30) as server:
            server.login(sender, app_password)
            server.sendmail(sender, [recipient], msg.as_string())
        logger.info(f"Email sent to {recipient}")
    except Exception as e:
        logger.error(f"Email send failed: {e}")
        raise
